# Generated by Django 4.1 on 2022-09-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_leader_post_bytime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leader_Post',
        ),
    ]
