# Generated by Django 4.1 on 2022-10-17 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_generator_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader_post_bytime',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
