# Generated by Django 4.1 on 2022-11-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_leader_post_bytime_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader_post_bytime',
            name='avatar',
        ),
    ]
