# Generated by Django 4.1 on 2022-10-17 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_leader_post_bytime_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader_post_bytime',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
