# Generated by Django 4.1 on 2022-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_alter_leader_post_bytime_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator_exercises',
            name='exercise_duration',
            field=models.CharField(max_length=120),
        ),
    ]
